site_name: Argo CD Operator
repo_url: https://github.com/argoproj-labs/argocd-operator
strict: true
theme:
  name: material
  palette:
    primary: teal
  font:
    text: 'Work Sans'
  logo: 'assets/logo.png'
extra_css:
  - 'assets/extra.css'
markdown_extensions:
- codehilite
- admonition
- toc:
    permalink: true
nav:
  - Overview: index.md
  - Install:
    - Getting Started: install/start.md
    - OpenShift: install/openshift.md
    - Operator Lifecycle Manager: install/olm.md
    - Manual Installation: install/manual.md
  - Usage: 
    - Basics: usage/basics.md
    - Ingress: usage/ingress.md
  - Reference:
    - ArgoCD: reference/argocd.md
    - ArgoCDExport: reference/argocdexport.md
    - API Docs: reference/api.html.md
  - Contributing: 
      - Development: 
          - Setup: contribute/development.md
          - OLM Environment: contribute/olm-env.md
  - Releases ⧉: https://github.com/argoproj-labs/argocd-operator/releases
  - Roadmap ⧉: https://github.com/argoproj-labs/argocd-operator/milestones
