apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: argocd-operator
  name: controller-manager-metrics-service
  namespace: system
spec:
  ports:
  - name: default-metrics
    port: 8080
    targetPort: 8080
  - name: custom-metrics
    port: 8085
    targetPort: 8085
  selector:
    control-plane: argocd-operator
