apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: argocd-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/jmckind/argocd-operator-registry@sha256:82d6ebd5bbfc9c2b1a5058d29dd01b7fee5e3557f4936c3ed47b633900513b11
  displayName: Argo CD Operators
  publisher: Argo CD Community
