apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: argocd-catalog
spec:
  sourceType: grpc
  image: quay.io/argoprojlabs/argocd-operator-registry@sha256:7cbeac22c6c4b98f525d6114664c953d13d68c26a861a4604bf544dc5f8f113d
  displayName: Argo CD Operators
  publisher: Argo CD Community
