apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: argocd-catalog
spec:
  sourceType: grpc
  image: quay.io/argoprojlabs/argocd-operator-registry@sha256:b1de26f7f61f7b9583a68db0cca977949b8a4de3fcefa318fae49c6308d0418f # 0.17.0
  displayName: Argo CD Operators
  publisher: Argo CD Community