apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-operator
subjects:
- kind: ServiceAccount
  name: argocd-operator
roleRef:
  kind: Role
  name: argocd-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-operator
subjects:
- kind: ServiceAccount
  name: argocd-operator
roleRef:
  kind: ClusterRole
  name: argocd-operator
  apiGroup: rbac.authorization.k8s.io