---
# Use `replaces-mode` or `semver-mode`. Once you switch to `semver-mode`, there is no easy way back.
updateGraph: replaces-mode
reviewers:
  - iam-veeramalla
  - jannfis
  - jomkz
  - jopit
  - wtam2018
