name: Generated code
on:
  push:
    branches:
    - 'master'
  pull_request:
    paths-ignore:
      - "docs/**"
    branches:
      - 'master'

jobs:
  check-go-modules:
    name: "Check for go.mod/go.sum synchronicity"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Golang
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Download all Go modules
        run: |
          go mod download
      - name: Check for tidyness of go.mod and go.sum
        run: |
          go mod tidy
          git diff --exit-code -- .

  check-sdk-codegen:
    name: "Check for changes from make bundle"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Golang
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'        
      - name: Run make bundle
        run: |
          make bundle
      - name: Ensure there is no diff in bundle
        # --ignore-matching-lines='.*createdAt:.*' added to ignore bundle differences of timestamp that is generated by upgraded operator-sdk
        run: |
          git diff --ignore-matching-lines='.*createdAt:.*' --exit-code -- .
      - name: Run make generate
        run: |
          make generate
      - name: Ensure there is no diff in generated assets
        run: |
          git diff --ignore-matching-lines='.*createdAt:.*' --exit-code -- .
      - name: Run make manifests
        run: |
          make manifests
      - name: Ensure there is no diff in manifests
        run: |
          git diff --ignore-matching-lines='.*createdAt:.*' --exit-code -- .
