name: Code scans
on:
  pull_request:
    paths-ignore:
      - "docs/**"
    branches:
      - 'master'
      - 'release-*'
      - 'rhos-*'

jobs:
  lint_code:
    name: Run golangci-lint and gosec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: "Ensure code passes 'go-sec' - run 'make gosec' to identify issues"
        run: |
          make gosec
      - name: "Ensure code passes 'golangci-lint' - run 'make lint' to identify issues"
        run: |
          make lint 
      - name: Ensure there is no diff in code
        run: |
          git diff --ignore-matching-lines='.*createdAt:.*' --exit-code -- .
