name: Publish latest operator build 
on:
  push:
    branches:
      - 'master'

jobs:

  publish-latest-operator:
    runs-on: ubuntu-latest

    env:
      ARGOCD_OPERATOR_IMAGE_BUILDER: docker
      ARGOCD_OPERATOR_IMAGE: ${{ secrets.REGISTRY_URL }}/argocd-operator:latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Restore go build cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-v1-${{ github.run_id }}

      - name: Install operator-sdk
        run: |
          sudo apt-get install git -y
          git clone https://github.com/operator-framework/operator-sdk ~/go/src/github.com/operator-framework/operator-sdk
          cd ~/go/src/github.com/operator-framework/operator-sdk
          git checkout v0.19.4
          make tidy
          make install

      - name: Build operator and Tag Latest
        run: bash hack/build.sh

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push latest operator
        run: bash hack/push.sh
